#!/bin/bash

tput setaf 4; echo [All] [Wrong] [Empty]; tput sgr0
read v1 v2 v3
let v4=v1-v2-v3
let s1=v1*3
let s2=v2*4
let s3=v3*3
let s4=s1-s2-s3
let s5=s4*10000/s1
let s6=s5/100
let s7=s5%100
echo 
echo "[All]:		`tput bold`$v1`tput sgr 0`"
echo "[Correct]:	`tput bold`$v4`tput sgr 0`"
echo "[Wrong]:	`tput bold`$v2`tput sgr 0`"
echo "[Empty]:	`tput bold`$v3`tput sgr 0`"
echo 
tput setaf 3; echo "[Score(-)]:	`tput bold`$s6.$s7`tput sgr 0`"; tput setaf 1
let s8=s5/1000
let s9=10-s8
echo -n "["
while [ $s8 -gt 0 ];
do
	echo -n "#"
	let s8=s8-1
done

while [ $s9 -gt 0 ];
do
	echo -n "-"
	let s9=s9-1
done
echo -n -e "]\n"
echo
let q2=v4*10000/v1
let q3=q2/100
let q4=q2%100
tput setaf 3; echo "[Score]:	`tput bold`$q3.$q4`tput sgr 0`"; tput setaf 1
let q5=q2/1000
let q6=10-q5
echo -n "["
while [ $q5 -gt 0 ];
do
	echo -n "#"
	let q5=q5-1
done

while [ $q6 -gt 0 ];
do
	echo -n "-"
	let q6=q6-1
done
echo -n -e "]\n"
echo 
read exitkey
